-- ============================================
-- Mollyverse: запусти ВЕСЬ файл в SQL Editor (New query → Run)
-- ============================================

-- 1) Колонки в posts
alter table public.posts
  add column if not exists user_id uuid references auth.users(id) on delete set null;

alter table public.posts
  add column if not exists post_source text not null default 'feed';

-- 2) Старые посты без автора — привязать к тебе (ЗАМЕНИ email на свой!)
-- update public.posts
-- set user_id = (select id from auth.users where email = 'ТВОЙ_EMAIL@example.com' limit 1)
-- where user_id is null;

-- 3) (необязательно) метка источника поста
-- update public.posts set post_source = 'profile' where post_source is null;

-- 4) Права
grant usage on schema public to authenticated, anon;
grant select, insert, update, delete on table public.posts to authenticated;
grant select on table public.posts to anon;
grant select, insert, update, delete on table public.profiles to authenticated;
grant select on table public.profiles to anon;

-- 5) RLS posts
alter table public.posts enable row level security;

drop policy if exists "posts_select_all" on public.posts;
drop policy if exists "posts_insert_own" on public.posts;
drop policy if exists "posts_update_own" on public.posts;
drop policy if exists "posts_delete_own" on public.posts;

create policy "posts_select_all"
on public.posts for select to authenticated
using (true);

create policy "posts_insert_own"
on public.posts for insert to authenticated
with check (auth.uid() = user_id);

create policy "posts_update_own"
on public.posts for update to authenticated
using (auth.uid() = user_id);

create policy "posts_delete_own"
on public.posts for delete to authenticated
using (auth.uid() = user_id);

-- 6) RLS profiles — ники видны всем залогиненным
alter table public.profiles enable row level security;

drop policy if exists "profiles_select_all_authenticated" on public.profiles;
drop policy if exists "Users can read own profile" on public.profiles;
drop policy if exists "Users can insert own profile" on public.profiles;
drop policy if exists "Users can update own profile" on public.profiles;

create policy "profiles_select_all_authenticated"
on public.profiles for select to authenticated
using (true);

create policy "Users can insert own profile"
on public.profiles for insert to authenticated
with check (auth.uid() = id);

create policy "Users can update own profile"
on public.profiles for update to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

-- 7) Лайки и избранное (см. также supabase/post_reactions.sql)
create table if not exists public.post_likes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  post_id uuid not null references public.posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, post_id)
);

create table if not exists public.post_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  post_id uuid not null references public.posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, post_id)
);

grant select, insert, delete on public.post_likes to authenticated;
grant select, insert, delete on public.post_favorites to authenticated;

alter table public.post_likes enable row level security;
alter table public.post_favorites enable row level security;

drop policy if exists "post_likes_select_own" on public.post_likes;
drop policy if exists "post_likes_insert_own" on public.post_likes;
drop policy if exists "post_likes_delete_own" on public.post_likes;

create policy "post_likes_select_authenticated"
on public.post_likes for select to authenticated
using (true);

create policy "post_likes_insert_own"
on public.post_likes for insert to authenticated
with check (auth.uid() = user_id);

create policy "post_likes_delete_own"
on public.post_likes for delete to authenticated
using (auth.uid() = user_id);

drop policy if exists "post_favorites_select_own" on public.post_favorites;
drop policy if exists "post_favorites_insert_own" on public.post_favorites;
drop policy if exists "post_favorites_delete_own" on public.post_favorites;

create policy "post_favorites_select_authenticated"
on public.post_favorites for select to authenticated
using (true);

create policy "post_favorites_insert_own"
on public.post_favorites for insert to authenticated
with check (auth.uid() = user_id);

create policy "post_favorites_delete_own"
on public.post_favorites for delete to authenticated
using (auth.uid() = user_id);

-- 8) Комментарии к постам (см. также supabase/post_comments.sql)
create table if not exists public.post_comments (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null check (char_length(trim(content)) > 0),
  created_at timestamptz not null default now()
);

create index if not exists post_comments_post_id_idx on public.post_comments (post_id);

grant select, insert, delete on public.post_comments to authenticated;

alter table public.post_comments enable row level security;

drop policy if exists "post_comments_select_authenticated" on public.post_comments;
drop policy if exists "post_comments_insert_own" on public.post_comments;
drop policy if exists "post_comments_delete_own" on public.post_comments;

create policy "post_comments_select_authenticated"
on public.post_comments for select to authenticated
using (true);

create policy "post_comments_insert_own"
on public.post_comments for insert to authenticated
with check (auth.uid() = user_id);

create policy "post_comments_delete_own"
on public.post_comments for delete to authenticated
using (auth.uid() = user_id);

-- 9) Аватарки (см. также supabase/profile_avatars.sql)
alter table public.profiles
  add column if not exists avatar_url text;

insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do update set public = true;

drop policy if exists "avatars_public_read" on storage.objects;
drop policy if exists "avatars_insert_own" on storage.objects;
drop policy if exists "avatars_update_own" on storage.objects;
drop policy if exists "avatars_delete_own" on storage.objects;

create policy "avatars_public_read"
on storage.objects for select
using (bucket_id = 'avatars');

create policy "avatars_insert_own"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "avatars_update_own"
on storage.objects for update to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "avatars_delete_own"
on storage.objects for delete to authenticated
using (
  bucket_id = 'avatars'
  and (storage.foldername(name))[1] = auth.uid()::text
);

-- 10) Фото постов (см. также supabase/post_images.sql)
alter table public.posts
  add column if not exists post_image_url text;

insert into storage.buckets (id, name, public)
values ('post-images', 'post-images', true)
on conflict (id) do update set public = true;

drop policy if exists "post_images_public_read" on storage.objects;
drop policy if exists "post_images_insert_own" on storage.objects;
drop policy if exists "post_images_update_own" on storage.objects;
drop policy if exists "post_images_delete_own" on storage.objects;

create policy "post_images_public_read"
on storage.objects for select
using (bucket_id = 'post-images');

create policy "post_images_insert_own"
on storage.objects for insert to authenticated
with check (
  bucket_id = 'post-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "post_images_update_own"
on storage.objects for update to authenticated
using (
  bucket_id = 'post-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

create policy "post_images_delete_own"
on storage.objects for delete to authenticated
using (
  bucket_id = 'post-images'
  and (storage.foldername(name))[1] = auth.uid()::text
);

-- Обновить кэш API после создания таблиц
notify pgrst, 'reload schema';
