-- Только лайки и избранное (если fix_all.sql уже запускали раньше)
-- Supabase → SQL Editor → New query → вставить → Run

create table if not exists public.post_likes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  post_id uuid not null references public.posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, post_id)
);

create table if not exists public.post_favorites (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  post_id uuid not null references public.posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (user_id, post_id)
);

grant select, insert, delete on public.post_likes to authenticated;
grant select, insert, delete on public.post_favorites to authenticated;

alter table public.post_likes enable row level security;
alter table public.post_favorites enable row level security;

drop policy if exists "post_likes_select_own" on public.post_likes;
drop policy if exists "post_likes_insert_own" on public.post_likes;
drop policy if exists "post_likes_delete_own" on public.post_likes;

create policy "post_likes_select_own"
on public.post_likes for select to authenticated
using (auth.uid() = user_id);

create policy "post_likes_insert_own"
on public.post_likes for insert to authenticated
with check (auth.uid() = user_id);

create policy "post_likes_delete_own"
on public.post_likes for delete to authenticated
using (auth.uid() = user_id);

drop policy if exists "post_favorites_select_own" on public.post_favorites;
drop policy if exists "post_favorites_insert_own" on public.post_favorites;
drop policy if exists "post_favorites_delete_own" on public.post_favorites;

create policy "post_favorites_select_own"
on public.post_favorites for select to authenticated
using (auth.uid() = user_id);

create policy "post_favorites_insert_own"
on public.post_favorites for insert to authenticated
with check (auth.uid() = user_id);

create policy "post_favorites_delete_own"
on public.post_favorites for delete to authenticated
using (auth.uid() = user_id);

notify pgrst, 'reload schema';
