-- Комментарии к постам (запусти в SQL Editor или через fix_all.sql)

create table if not exists public.post_comments (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.posts(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null check (char_length(trim(content)) > 0),
  created_at timestamptz not null default now()
);

create index if not exists post_comments_post_id_idx on public.post_comments (post_id);
create index if not exists post_comments_created_at_idx on public.post_comments (post_id, created_at);

grant select, insert, delete on public.post_comments to authenticated;

alter table public.post_comments enable row level security;

drop policy if exists "post_comments_select_authenticated" on public.post_comments;
drop policy if exists "post_comments_insert_own" on public.post_comments;
drop policy if exists "post_comments_delete_own" on public.post_comments;

create policy "post_comments_select_authenticated"
on public.post_comments for select to authenticated
using (true);

create policy "post_comments_insert_own"
on public.post_comments for insert to authenticated
with check (auth.uid() = user_id);

create policy "post_comments_delete_own"
on public.post_comments for delete to authenticated
using (auth.uid() = user_id);

notify pgrst, 'reload schema';
